# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a8192173dc6400cc4f490dfb8874fcb6c3310c64627a4793509f60884f8b25d3a21d4a52cd099e9ad34c115acffec447bc512b7ec615b03abd47228826522a

test:
  secret_key_base: f243ae079f5109e71d3da643f0ea717742ff4ad28f469827dc61661cac565b21345a58cb2c28d4e98f9061c6b8af067112ecf7e002ce0b77f78b5c965deef479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
